### ISSUE TITLE
[L] {Suggestion!} Users can edit and delete their own posts

### ISSUE THREAD

**Issue by BecaLParker** [GunelMC/acebook-runtime-terrors#16]
While @GoWebMe2020 and I were working on the display for posts in views>posts>index.html.erb we oringinally started making some buttons for edit/delete etc on each post but JP suggest making these a hamburger drop down on each post so I'm creating this ticket so we don't loose that awesome idea!

Code for edit/delete etc buttons should be visible as commented out in in views>posts>index.html.erb at our PR for 'displaying posts in reverse chronological order'

**Comment by GoWebMe2020** [comment]
Add edit, delete and show buttons to posts
Owners can see edit, show and delete buttons
Non-owners can only see show.
Later: Hamber dropdown menu
