### ISSUE TITLE
[S/M] Posts appear with the newest post first

### ISSUE THREAD

**Issue by Dev-ops-true** [GunelMC/acebook-runtime-terrors#4]
![image](https://user-images.githubusercontent.com/75490778/122087495-b0682500-cdfc-11eb-9e7c-e1b20813a31a.png)

 

- [x] Decorate post page (comment bit to hook later)

- [x] button for like to hook up later

**Comment by BecaLParker** [comment]
![image](https://user-images.githubusercontent.com/75490778/122086639-ce815580-cdfb-11eb-832e-14d92c567361.png)

**Comment by BecaLParker** [comment]
- [x] Decorate post page (comment bit to hook later)
- [x] button for like to hook up later
