### ISSUE TITLE
[M/L] Users can comment on posts

### ISSUE THREAD

**Issue by Dev-ops-true** [GunelMC/acebook-runtime-terrors#5]
![image](https://user-images.githubusercontent.com/75490778/122087604-ce358a00-cdfc-11eb-84d3-b02feb6cacde.png)

**Comment by BecaLParker** [comment]
![image](https://user-images.githubusercontent.com/75490778/122086789-f2dd3200-cdfb-11eb-834a-beee447cbb3e.png)
